services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src/data:/app/src/data
      - ./cache:/app/cache
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - mobility-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - mobility-network

networks:
  mobility-network:
    driver: bridge
