activate_visualisation: false
buffer_layer:
  stations_bixi:
    buffer_type: circular
    distance: 120
    geometry_type: Point
colors:
  od_2018: '[0, 0, 0, 0]'
  reseau_cyclable: '[0, 0, 0, 0]'
  stations_bixi: '[0, 0, 0, 0]'
  stm_bus_stops: '[0, 0, 0, 0]'
  uniteevaluationfonciere: '[0, 0, 0, 0]'
count_columns:
- stop_id as count_arret_bus
- feuillet as count_nb_menage
- ID_UEV as count_num_bati
count_distinct_columns:
- station_id as count_bixi_station
data_files:
- name: od_2018
  path: ./data/input/geojson/od_2018.geojson
- name: reseau_cyclable
  path: ./data/input/geojson/reseau_cyclable.geojson
- name: stations_bixi
  path: ./data/input/geojson/stations_bixi.geojson
- name: stm_bus_stops
  path: ./data/input/geojson/stm_bus_stops.geojson
- name: uniteevaluationfonciere
  path: ./data/input/geojson/uniteevaluationfonciere.geojson
filter_data_files:
  stations_bixi:
    column: capacity
    operator: '>='
    value: 40
filter_global:
- column: count_arret_bus_count
  operator: '>'
  value: 0
groupby_columns:
- buffer_id
- name
join_layers:
  linestrings:
    type: intersects
  multipolygons:
    type: intersects
  points:
    type: contains
  polygons:
    type: intersects
max_columns:
- capacity as max_capacity
mean_columns:
- SUPERFICIE_TERRAIN as moy_superficie_terrain
- LONGUEUR as moy_long_piste_cy
min_columns:
- capacity as min_capacity
ratio_columns:
- denominator: perslogi
  name: permis_perslogi_ratio
  numerator: permis
std_columns:
- SUPERFICIE_TERRAIN as std_superficie_terrain
sum_columns:
- permis as total_permis
- autologi as total_autologi
