data_files:
  bixi_stations: ./data/input/geojson/stations_bixi.geojson
  bus_stops: ./data/input/geojson/stm_bus_stops.geojson
  evaluation_fonciere: ./data/input/geojson/uniteevaluationfonciere.geojson
  menage_2018: ./data/input/geojson/od_2018.geojson
  reseau_cyclable: ./data/input/geojson/reseau_cyclable.geojson
buffer_layer:
  bixi_stations:
    distance: 500
    geometry_type: Point
count_distinct_columns:
- station_id as count_bixi_station
filter_data_files:
  bixi_stations:
    column: capacity
    operator: '>='
    value: 0
groupby_columns:
- buffer_id
- name
join_layers:
  linestrings:
    type: intersects
  multipolygons:
    type: intersects
  points:
    type: contains
  polygons:
    type: intersects
ratio_columns:
  permis_perslogi_ratio:
    denominator: perslogi
    numerator: permis
sum_columns:
- permis as total_permis
- autologi as total_autologi
colors:
  bixi_stations: '[200, 30, 0, 160]'
  bus_stops: '[0, 200, 0, 160]'
  evaluation_fonciere: '[0, 30, 200, 160]'
  menage_2018: '[255, 255, 0, 160]'
  reseau_cyclable: '[255, 165, 0, 160]'