activate_visualisation: true
buffer_layer:
  stations_bixi:
    buffer_type: circular
    distance: 1000
    geometry_type: Point
colors:
  mtlzonage: '[0, 0, 0, 0]'
  od_2018agg: '[0, 200, 0, 160]'
  stations_bixi: '[200, 30, 0, 160]'
count_columns:
- feuillet as count_nb_menage
count_distinct_columns:
- station_id as count_bixi_station
data_files:
- name: od_2018agg
  path: ./data/input/geojson/od_2018agg.geojson
- name: stations_bixi
  path: ./data/input/geojson/stations_bixi.geojson
filter_data_files: {}
filter_global: []
groupby_columns:
- buffer_id
- name
histogram_config:
  aggregation:
    type: count
  binsize: 10
  columns:
  - age
  groupby: name
join_layers:
  linestrings:
    type: intersects
  multipolygons:
    type: intersects
  points:
    type: contains
  polygons:
    type: intersects
max_columns:
- capacity as max_capacity
mean_columns: []
min_columns:
- capacity as min_capacity
ratio_columns:
- denominator: perslogi
  name: autologi_perslogi_ratio
  numerator: autologi
std_columns: []
sum_columns:
- permis as total_permis
- autologi as total_autologi
