##TODO ajouter sum
##TODO ajouter renaming groupby_columns
##TODO improve speed for network buffer
##TODO find a solution for improving map performance
##TODO Regarder pour utiliser cache pour tableau
##TODO changer formatage du ratio_colums pour prendre une liste.
##TODO Validation données et jointure (Revoir multipolygon).
##TODO pouvoir gérer plusieurs data input.
##TODO ajouter commentaire + README
##TODO ajouter des distributions
##TODO check if two columns have the same name
##TODO ajouter naming pour buffer
##TODO check comment il ferme le buffer convex hull, ligne droite ??
##TODO TODO ajouter buffer autour lignes, polygons et multipolygon
##TODO ajouter logique du code dans memoire
##TODO un point peut avoir une ponderation e.g (une station bixi avec 3 points ancrage vs 50 pts)
##TODO commencer un chapitre resultat (presentation de l'outil)
##TODO ajouter matrice lien entre les objets
##TODO methode des noyaux
##TODO isochrones
##TODO AJOUTER FILTERING
##TODO presentaiton prendre source de donnee random et tester

data_files:
  bus_stops: "./data/input/geojson/stm_bus_stops.geojson"
  bixi_stations: "./data/input/geojson/stations_bixi.geojson"
  evaluation_fonciere: "./data/input/geojson/uniteevaluationfoncieretest.geojson"
  menage_2018: "./data/input/geojson/od_2018.geojson"
  reseau_cyclable: "./data/input/geojson/reseau_cyclable.geojson"

filter_columns:
  bus_stops:
    column:
    value:
  bixi_stations:
    column: "capacity"
    value: 50
    operator: ">="

ratio_columns:
  - "permis"
  - "perslogi"

max_columns:
  - "capacity"
  
min_columns:

mean_columns:
  - "SUPERFICIE_TERRAIN as moy_superficie_terrain"
  - "LONGUEUR as moy_long_piste_cy"

std_columns:

count_columns:
  - "stop_id as count_arret_bus"
  - "feuillet as count_nb_menage"
  - "ID_UEV as count_num_bati"

groupby_columns:
  - "buffer_id"
  - "name"

buffer_type: "apply_buffer" #apply_isochrones

buffer_layer:
  bixi_stations: 1000

activate_visualisation: false

join_layers:
  points:
    type: "contains"
  polygons:
    type: "intersects"
  multipolygons:
    type: "intersects"
  linestrings:
    type: "intersects"
  
colors:
  bus_stops: "[0, 200, 0, 160]"
  bixi_stations: "[200, 30, 0, 160]"
  evaluation_fonciere: "[0, 30, 200, 160]"
  menage_2018: "[255, 255, 0, 160]"
  reseau_cyclable: "[255, 165, 0, 160]"