activate_visualisation: true
buffer_layer:
  stations_bixi:
    buffer_type: circular
    distance: 500
    geometry_type: Point
colors:
  mtlzonage: '[0, 0, 0, 0]'
  od_2018agg: '[200, 30, 0, 160]'
  stations_bixi: '[200, 30, 0, 160]'
count_columns: []
count_distinct_columns: []
data_files:
- name: od_2018agg
  path: ./data/input/geojson/od_2018agg.geojson
- name: stations_bixi
  path: ./data/input/geojson/stations_bixi.geojson
filter_data_files: {}
filter_global: []
groupby_columns:
- buffer_id
- name
histogram_config:
  aggregation:
    column: autologi
    type: sum
  binsize: 2
  columns:
  - AUTOLOGI
  groupby: name
join_layers:
  linestrings:
    type: intersects
  multipolygons:
    type: intersects
  points:
    type: contains
  polygons:
    type: intersects
max_columns: []
mean_columns: []
min_columns: []
multiply_columns:
- columns:
  - faclog_s27
  - autologi
  name: faclog_autologi
ratio_columns: []
std_columns: []
sum_columns:
- facper_s27 as total_pers
- autologi as total_autologi
