activate_visualisation: true
buffer_layer:
  points_geojson:
    buffer_type: circular
    distance: 200
    geometry_type: Point
colors:
  lines_geojson: '[255, 165, 0, 160]'
  points_geojson: '[255, 0, 0, 160]'
  polygons_geojson: '[0, 255, 0, 160]'
count_columns: []
count_distinct_columns:
- line_name as nbr_line
- polygon_name as nbr_polygon
data_files:
- name: lines_geojson
  path: ./data/input/geojson/lines_geojson.geojson
- name: points_geojson
  path: ./data/input/geojson/points_geojson.geojson
- name: polygons_geojson
  path: ./data/input/geojson/polygons_geojson.geojson
filter_data_files: {}
filter_global: []
groupby_columns:
- buffer_id
- point_name
join_layers:
  linestrings:
    type: intersects
  multipolygons:
    type: intersects
  points:
    type: contains
  polygons:
    type: intersects
max_columns: []
mean_columns: []
min_columns: []
multiply_columns: []
post_aggregation_metrics: {}
ratio_columns: []
std_columns: []
sum_columns: []
