activate_visualisation: true
buffer_layer:
  mtlzonage:
    buffer_type: zones
    geometry_type: MultiPolygon
colors:
  mtlzonage: '[200, 30, 0, 160]'
  od_2018test: '[255, 255, 0, 160]'
  reseau_cyclabletest: '[255, 165, 0, 160]'
  stations_bixi: '[200, 30, 0, 160]'
  stm_bus_stops: '[200, 30, 0, 160]'
  uniteevaluationfoncieretest: '[0, 30, 200, 160]'
count_columns:
- stop_id as count_arret_bus
- feuillet as count_nb_menage
- ID_UEV as count_num_bati
count_distinct_columns:
- station_id as count_bixi_station
data_files:
- name: mtlzonage
  path: ./data/input/geojson/mtlzonage.geojson
- name: od_2018test
  path: ./data/input/geojson/od_2018test.geojson
- name: reseau_cyclabletest
  path: ./data/input/geojson/reseau_cyclabletest.geojson
- name: stations_bixi
  path: ./data/input/geojson/stations_bixi.geojson
- name: stm_bus_stops
  path: ./data/input/geojson/stm_bus_stops.geojson
- name: uniteevaluationfoncieretest
  path: ./data/input/geojson/uniteevaluationfoncieretest.geojson
filter_data_files: {}
filter_global:
- column: count_arret_bus_count
  operator: '>='
  value: 0
groupby_columns:
- NOM
join_layers:
  linestrings:
    type: intersects
  multipolygons:
    type: intersects
  points:
    type: contains
  polygons:
    type: intersects
max_columns:
- capacity as max_capacity
mean_columns:
- SUPERFICIE_TERRAIN as moy_superficie_terrain
- LONGUEUR as moy_long_piste_cy
min_columns:
- capacity as min_capacity
ratio_columns:
- denominator: perslogi
  name: permis_perslogi_ratio
  numerator: permis
std_columns:
- SUPERFICIE_TERRAIN as std_superficie_terrain
sum_columns:
- permis as total_permis
- autologi as total_autologi

histogram_config:
  columns:  
    - "age"
  binsize: 10
  groupby: "NOM"  # This can be set to None or removed if you don't want grouping
  aggregation: 
    type: "sum"  # count or "sum"
    column: "facper_s27"  # This is ignored if type is "count". If type is "sum", specify the column name here.